// <auto-generated />
using CarGaugesApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarGaugesApi.Migrations
{
    [DbContext(typeof(CarGaugesDbContext))]
    [Migration("20190405121545_ManyToMany")]
    partial class ManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarGaugesApi.Models.Device", b =>
                {
                    b.Property<string>("BluetoothAddress")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("BluetoothAddress");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("CarGaugesApi.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("Description");

                    b.Property<int>("MeasurementSystem");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Token");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CarGaugesApi.Models.UserDevice", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("DeviceAddress");

                    b.HasKey("UserId", "DeviceAddress");

                    b.HasIndex("DeviceAddress");

                    b.ToTable("UserDevice");
                });

            modelBuilder.Entity("CarGaugesApi.Models.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceAddress");

                    b.Property<int>("Duration");

                    b.HasKey("Id");

                    b.ToTable("Work");
                });

            modelBuilder.Entity("CarGaugesApi.Models.UserDevice", b =>
                {
                    b.HasOne("CarGaugesApi.Models.Device", "Device")
                        .WithMany("DeviceUsers")
                        .HasForeignKey("DeviceAddress")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarGaugesApi.Models.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
